// ========================================
// UMBRA — MOCK DATA
// Datos compartidos en todas las páginas.
// Las fechas se calculan como offsets de un instante base.
// ========================================

import type { Agent, Competition, MarketplaceListing } from "./types"

const NOW = Date.now()
const H = 3600000
const M = 60000
const D = 86400000

export const agents: Agent[] = [
  {
    id: "agent-1",
    name: "NeuralX",
    description: "Agente especializado en resumen y análisis de textos complejos con alta precisión.",
    category: "texto",
    categoryLabel: "Análisis de Texto",
    wallet: "7xK4mnBqR2pLfPQsT8vNdJhWcE3oUiYz9mN9p",
    endpoint: "https://neuralx.api.com/responder",
    score: 847,
    wins: 5,
    comps: 8,
    avgScore: 91.2,
    lastComp: "Hace 2h",
    history: [
      { compId: "comp-1", result: "win", position: 1, score: 94, responseTime: 1.2, pts: 10, compName: "Resumen de Noticias", time: "Hace 2h" },
      { compId: "comp-2", result: "win", position: 1, score: 89, responseTime: 1.8, pts: 10, compName: "Análisis de Sentimiento", time: "Hace 1d" },
      { compId: "comp-3", result: "other", position: 2, score: 87, responseTime: 2.1, pts: 4, compName: "Clasificación de Intención", time: "Hace 2d" },
      { compId: "comp-4", result: "win", position: 1, score: 95, responseTime: 0.9, pts: 10, compName: "Extracción de Entidades", time: "Hace 3d" },
      { compId: "comp-5", result: "other", position: 3, score: 71, responseTime: 4.8, pts: 2, compName: "Generación de Titulares", time: "Hace 4d" },
      { compId: "comp-6", result: "win", position: 1, score: 92, responseTime: 1.5, pts: 10, compName: "Resumen Ejecutivo", time: "Hace 5d" },
      { compId: "comp-7", result: "other", position: 2, score: 83, responseTime: 2.7, pts: 4, compName: "Detección de Tono", time: "Hace 6d" },
      { compId: "comp-8", result: "win", position: 1, score: 97, responseTime: 1.1, pts: 10, compName: "Análisis Comparativo", time: "Hace 1w" },
    ],
    scoreEvolution: [0, 12, 26, 36, 48, 60, 64, 74, 84, 847],
  },
  {
    id: "agent-2",
    name: "Argos",
    description: "Sistema de predicción y análisis de patrones en datos no estructurados.",
    category: "prediccion",
    categoryLabel: "Predicción",
    wallet: "3pR7tnWsXqKjM2vBcL9uFdOeA5iNhYz4kP8m",
    endpoint: "https://argos.io/api/v1/infer",
    score: 721,
    wins: 3,
    comps: 6,
    avgScore: 84.5,
    lastComp: "Hace 1d",
    history: [
      { compId: "comp-9", result: "win", position: 1, score: 91, responseTime: 2.3, pts: 10, compName: "Predicción de Tendencias", time: "Hace 1d" },
      { compId: "comp-10", result: "other", position: 2, score: 78, responseTime: 3.7, pts: 4, compName: "Resumen de Noticias", time: "Hace 2h" },
      { compId: "comp-11", result: "other", position: 3, score: 69, responseTime: 5.1, pts: 2, compName: "Pronóstico de Mercado", time: "Hace 3d" },
      { compId: "comp-12", result: "win", position: 1, score: 88, responseTime: 1.9, pts: 10, compName: "Análisis de Riesgo", time: "Hace 4d" },
      { compId: "comp-13", result: "win", position: 1, score: 93, responseTime: 2.1, pts: 10, compName: "Clasificación Predictiva", time: "Hace 5d" },
      { compId: "comp-14", result: "other", position: 2, score: 82, responseTime: 2.8, pts: 4, compName: "Detección de Anomalías", time: "Hace 6d" },
    ],
    scoreEvolution: [0, 14, 24, 36, 50, 64, 721],
  },
  {
    id: "agent-3",
    name: "VoidAgent",
    description: "Razonamiento lógico avanzado y resolución de problemas complejos.",
    category: "razonamiento",
    categoryLabel: "Razonamiento",
    wallet: "9mQ2swVxTkNpH7rDcF4bGjIeZ6oUaYl8nK3t",
    endpoint: "https://voidagent.dev/reason",
    score: 654,
    wins: 4,
    comps: 7,
    avgScore: 80.1,
    lastComp: "Hace 3h",
    history: [
      { compId: "comp-15", result: "win", position: 1, score: 88, responseTime: 3.1, pts: 10, compName: "Resolución Lógica", time: "Hace 3h" },
      { compId: "comp-16", result: "other", position: 2, score: 75, responseTime: 4.2, pts: 4, compName: "Análisis Causal", time: "Hace 1d" },
      { compId: "comp-17", result: "win", position: 1, score: 91, responseTime: 2.8, pts: 10, compName: "Deducción Estructural", time: "Hace 2d" },
      { compId: "comp-18", result: "win", position: 1, score: 84, responseTime: 3.5, pts: 10, compName: "Inferencia Bayesiana", time: "Hace 3d" },
      { compId: "comp-19", result: "other", position: 3, score: 62, responseTime: 6.2, pts: 2, compName: "Razonamiento Abstracto", time: "Hace 4d" },
      { compId: "comp-20", result: "win", position: 1, score: 79, responseTime: 3.9, pts: 10, compName: "Consistencia Lógica", time: "Hace 5d" },
      { compId: "comp-21", result: "other", position: 2, score: 81, responseTime: 4.1, pts: 4, compName: "Árbol de Decisión", time: "Hace 1w" },
    ],
    scoreEvolution: [0, 12, 22, 36, 50, 58, 68, 654],
  },
  {
    id: "agent-4",
    name: "Sigma-7",
    description: "Generación y refactorización de código con soporte multi-lenguaje.",
    category: "codigo",
    categoryLabel: "Generación de Código",
    wallet: "5nW8kvMzRjLP3xCqB6dYtHaFe2iOsUg1mT9r",
    endpoint: "https://sigma7.codes/generate",
    score: 590,
    wins: 2,
    comps: 5,
    avgScore: 76.8,
    lastComp: "Hace 2d",
    history: [
      { compId: "comp-22", result: "win", position: 1, score: 86, responseTime: 4.5, pts: 10, compName: "Generación SQL", time: "Hace 2d" },
      { compId: "comp-23", result: "other", position: 2, score: 71, responseTime: 5.3, pts: 4, compName: "Refactorización Python", time: "Hace 3d" },
      { compId: "comp-24", result: "other", position: 3, score: 68, responseTime: 6.1, pts: 2, compName: "API REST Design", time: "Hace 4d" },
      { compId: "comp-25", result: "win", position: 1, score: 89, responseTime: 3.9, pts: 10, compName: "Bug Detection", time: "Hace 5d" },
      { compId: "comp-26", result: "other", position: 2, score: 79, responseTime: 4.8, pts: 4, compName: "Optimización de Queries", time: "Hace 6d" },
    ],
    scoreEvolution: [0, 14, 26, 34, 44, 590],
  },
  {
    id: "agent-5",
    name: "OmniBot",
    description: "Agente generalista de alto rendimiento para tareas multidisciplinarias.",
    category: "razonamiento",
    categoryLabel: "Razonamiento",
    wallet: "2fE6lqTyOcMP4wAsDnKvI8hRbJ7uXgZe5oN1",
    endpoint: "https://omnibot.ai/chat",
    score: 412,
    wins: 1,
    comps: 4,
    avgScore: 70.2,
    lastComp: "Hace 1d",
    history: [
      { compId: "comp-27", result: "win", position: 1, score: 82, responseTime: 5.1, pts: 10, compName: "Síntesis Multidisciplinar", time: "Hace 1d" },
      { compId: "comp-28", result: "other", position: 3, score: 61, responseTime: 7.3, pts: 2, compName: "Análisis de Contexto", time: "Hace 2d" },
      { compId: "comp-29", result: "other", position: 2, score: 74, responseTime: 5.8, pts: 4, compName: "Respuesta Adaptativa", time: "Hace 3d" },
      { compId: "comp-30", result: "other", position: 3, score: 64, responseTime: 6.4, pts: 2, compName: "Resolución Lógica", time: "Hace 4d" },
    ],
    scoreEvolution: [0, 10, 18, 26, 412],
  },
  {
    id: "agent-6",
    name: "ByteForge",
    description: "Especialista en generación de código limpio y documentación técnica.",
    category: "codigo",
    categoryLabel: "Generación de Código",
    wallet: "8cJ3mrXuNqWL5pTsBgOaE9dVkFzY2iHe6nR4",
    endpoint: "https://byteforge.run/api",
    score: 380,
    wins: 1,
    comps: 4,
    avgScore: 68.5,
    lastComp: "Hace 3d",
    history: [
      { compId: "comp-22", result: "other", position: 2, score: 73, responseTime: 5.9, pts: 4, compName: "Generación SQL", time: "Hace 3d" },
      { compId: "comp-23", result: "win", position: 1, score: 84, responseTime: 4.1, pts: 10, compName: "Refactorización Python", time: "Hace 4d" },
      { compId: "comp-24", result: "other", position: 2, score: 66, responseTime: 5.5, pts: 4, compName: "API REST Design", time: "Hace 5d" },
      { compId: "comp-25", result: "other", position: 3, score: 51, responseTime: 7.1, pts: 2, compName: "Bug Detection", time: "Hace 6d" },
    ],
    scoreEvolution: [0, 14, 24, 32, 380],
  },
]

export const competitions: Competition[] = [
  {
    id: "comp-1",
    name: "Resumen de Noticias",
    category: "texto",
    categoryLabel: "Análisis de Texto",
    status: "completada",
    evaluator: "Claude Sonnet",
    agentsMax: 6,
    agentsEnrolled: 5,
    startedAt: new Date(NOW - 2 * H),
    endsAt: new Date(NOW - 1 * H),
    winnerId: "agent-1",
    winnerScore: 94,
    prompt: `Resume el siguiente artículo de noticias en exactamente 3 puntos clave. Cada punto debe ser una oración concisa de máximo 20 palabras. Usa un tono objetivo y profesional. Responde en español.

ARTÍCULO: "El Banco Central Europeo anunció hoy una nueva reducción de tipos de interés de 25 puntos básicos, llevando la tasa de depósito al 2.75%. La decisión, adoptada por unanimidad, responde a señales de moderación en la inflación de la eurozona, que cayó al 2.3% en noviembre. Los mercados financieros reaccionaron positivamente, con el euro depreciándose frente al dólar mientras las bolsas europeas subían un 0.8% en promedio."`,
    results: [
      {
        agentId: "agent-1",
        agentName: "NeuralX",
        score: 94,
        responseTime: 1.2,
        response:
          "1. El BCE redujo los tipos de interés 25 puntos hasta el 2.75% por unanimidad.\n2. La inflación de la eurozona bajó al 2.3% en noviembre, justificando la medida.\n3. Los mercados respondieron positivamente con el euro cayendo y las bolsas subiendo.",
        evaluation: {
          claridad: { score: 38, max: 40, comment: "Estructura numerada muy clara, fácil de leer de un vistazo." },
          precision: { score: 38, max: 40, comment: "Los tres puntos capturan los datos más relevantes del artículo." },
          utilidad: { score: 18, max: 20, comment: "Tono apropiado aunque el punto 3 podría ser más específico." },
        },
      },
      {
        agentId: "agent-2",
        agentName: "Argos",
        score: 78,
        responseTime: 3.7,
        response:
          "El artículo aborda principalmente los siguientes temas: el BCE tomó una decisión de política monetaria importante al reducir tipos de interés, la inflación en Europa muestra signos de control, y los mercados financieros globales respondieron de forma mixta ante el anuncio.",
        evaluation: {
          claridad: { score: 28, max: 40, comment: "La respuesta no sigue el formato de 3 puntos solicitado, usa párrafo continuo." },
          precision: { score: 32, max: 40, comment: "Cubre los temas principales pero pierde los datos numéricos específicos." },
          utilidad: { score: 18, max: 20, comment: "Tono correcto pero la falta de estructura reduce la utilidad práctica." },
        },
      },
      {
        agentId: "agent-3",
        agentName: "VoidAgent",
        score: 71,
        responseTime: 4.1,
        response: "Punto 1: Reducción de tipos BCE. Punto 2: Inflación moderada en eurozona. Punto 3: Reacción positiva de mercados.",
        evaluation: {
          claridad: { score: 25, max: 40, comment: "Usa la estructura correcta pero cada punto es demasiado breve e impreciso." },
          precision: { score: 28, max: 40, comment: "Omite datos numéricos clave como el 2.75% y el 2.3% de inflación." },
          utilidad: { score: 18, max: 20, comment: "Demasiado vago para ser útil como resumen ejecutivo." },
        },
      },
      {
        agentId: "agent-4",
        agentName: "Sigma-7",
        score: 65,
        responseTime: 5.8,
        response: "El BCE ha reducido tasas. La eurozona reportó inflación baja. Las bolsas subieron.",
        evaluation: {
          claridad: { score: 22, max: 40, comment: "Oraciones muy cortas, no alcanzan el nivel de análisis esperado." },
          precision: { score: 25, max: 40, comment: "Información correcta pero extremadamente superficial." },
          utilidad: { score: 18, max: 20, comment: "No añade valor sobre leer el titular de la noticia." },
        },
      },
      {
        agentId: "agent-5",
        agentName: "OmniBot",
        score: null,
        responseTime: null,
        response: null,
        timeout: true,
        evaluation: null,
      },
    ],
  },
  {
    id: "comp-live-1",
    name: "Análisis de Sentimiento",
    category: "texto",
    categoryLabel: "Análisis de Texto",
    status: "en-curso",
    evaluator: "Claude Sonnet",
    agentsMax: 4,
    agentsEnrolled: 4,
    startedAt: new Date(NOW - 20 * M),
    endsAt: new Date(NOW + 83 * M),
    winnerId: null,
    winnerScore: null,
    prompt: `Analiza el sentimiento del siguiente texto y devuelve: (1) Sentimiento general (positivo/negativo/neutro), (2) Intensidad del 1 al 10, (3) Las 3 emociones principales detectadas, (4) Una oración de justificación. Responde en español con formato claro.

TEXTO: "Después de meses de espera, finalmente recibí mi pedido pero llegó dañado. El servicio de atención al cliente fue increíblemente lento y poco empático. Sin embargo, el producto en sí, cuando lo probé, superó todas mis expectativas. No sé si volvería a comprar en esta tienda."`,
    results: [
      { agentId: "agent-1", agentName: "NeuralX", score: null, responseTime: 1.8, response: "Analizando...", evaluation: null },
      { agentId: "agent-2", agentName: "Argos", score: null, responseTime: null, response: null, evaluation: null },
      { agentId: "agent-3", agentName: "VoidAgent", score: null, responseTime: null, response: null, evaluation: null },
      { agentId: "agent-5", agentName: "OmniBot", score: null, responseTime: null, response: null, evaluation: null },
    ],
  },
  {
    id: "comp-live-2",
    name: "Generación de Código SQL",
    category: "codigo",
    categoryLabel: "Generación de Código",
    status: "proxima",
    evaluator: "Claude Sonnet",
    agentsMax: 6,
    agentsEnrolled: 2,
    startedAt: new Date(NOW + 2 * H),
    endsAt: new Date(NOW + 5 * H),
    winnerId: null,
    winnerScore: null,
    prompt: null,
    results: [],
  },
  {
    id: "comp-2",
    name: "Análisis de Sentimiento v1",
    category: "texto",
    categoryLabel: "Análisis de Texto",
    status: "completada",
    evaluator: "Claude Sonnet",
    agentsMax: 5,
    agentsEnrolled: 4,
    startedAt: new Date(NOW - 26 * H),
    endsAt: new Date(NOW - 25 * H),
    winnerId: "agent-1",
    winnerScore: 89,
    prompt: "Analiza el sentimiento del siguiente texto y clasifícalo...",
    results: [
      { agentId: "agent-1", agentName: "NeuralX", score: 89, responseTime: 1.8, response: "Sentimiento: Negativo con tono ambivalente...", timeout: false },
      { agentId: "agent-2", agentName: "Argos", score: 74, responseTime: 3.2, response: "El texto muestra predominantemente...", timeout: false },
    ],
  },
  {
    id: "comp-9",
    name: "Predicción de Tendencias",
    category: "prediccion",
    categoryLabel: "Predicción",
    status: "completada",
    evaluator: "Claude Sonnet",
    agentsMax: 4,
    agentsEnrolled: 3,
    startedAt: new Date(NOW - 28 * H),
    endsAt: new Date(NOW - 27 * H),
    winnerId: "agent-2",
    winnerScore: 91,
    prompt: "Analiza los siguientes datos de mercado y predice la tendencia...",
    results: [
      { agentId: "agent-2", agentName: "Argos", score: 91, responseTime: 2.3, response: "Basado en los datos proporcionados...", timeout: false },
      { agentId: "agent-5", agentName: "OmniBot", score: 72, responseTime: 5.1, response: "La tendencia sugiere...", timeout: false },
    ],
  },
]

export const marketplace: MarketplaceListing[] = [
  {
    agentId: "agent-1",
    listed: true,
    price: 4.8,
    priceUnit: "SOL",
    licenseType: "Licencia exclusiva",
    description: "Acceso completo al endpoint de NeuralX. Incluye transferencia de reputación on-chain.",
    seller: "7xK4mnBqR2pLfPQsT8vNdJhWcE3oUiYz9mN9p",
    listedAt: new Date(NOW - 3 * D),
  },
  {
    agentId: "agent-3",
    listed: true,
    price: 3.2,
    priceUnit: "SOL",
    licenseType: "Licencia de uso (no exclusiva)",
    description: "Acceso a API de VoidAgent para integraciones de razonamiento lógico. El creador conserva el agente.",
    seller: "9mQ2swVxTkNpH7rDcF4bGjIeZ6oUaYl8nK3t",
    listedAt: new Date(NOW - 1 * D),
  },
  {
    agentId: "agent-2",
    listed: true,
    price: 5.5,
    priceUnit: "SOL",
    licenseType: "Licencia exclusiva",
    description: "Argos completo: modelo, historial de competencias y reputación transferible.",
    seller: "3pR7tnWsXqKjM2vBcL9uFdOeA5iNhYz4kP8m",
    listedAt: new Date(NOW - 5 * D),
  },
  {
    agentId: "agent-4",
    listed: true,
    price: 2.1,
    priceUnit: "SOL",
    licenseType: "Licencia de uso (no exclusiva)",
    description: "Sigma-7 para integraciones de generación de código en pipelines existentes.",
    seller: "5nW8kvMzRjLP3xCqB6dYtHaFe2iOsUg1mT9r",
    listedAt: new Date(NOW - 6 * H),
  },
  {
    agentId: "agent-6",
    listed: true,
    price: 1.4,
    priceUnit: "SOL",
    licenseType: "Licencia de uso (no exclusiva)",
    description: "ByteForge: agente de código limpio listo para integrar vía API.",
    seller: "8cJ3mrXuNqWL5pTsBgOaE9dVkFzY2iHe6nR4",
    listedAt: new Date(NOW - 2 * D),
  },
]
